# -*- coding: utf-8 -*-
"""
Created on Sun Apr 14 20:47:53 2019

@author: pengz
"""

'''
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
def findTheDifference(s: str, t: str) -> str:   ## Using dict, written by my own
    ret = {}
    for item in s:
        if item not in ret.keys():
            ret[item] = 1
        else:
            ret[item] += 1
    for char in t:
        if char not in ret.keys() or ret[char] == 0:        
            return char
        else:
            ret[char] -= 1
            
a = findTheDifference('abcd','abcde')

def findTheDifference2(s,t):   ## Sort first, then compare, written by my own. seems faster than the first
    s = sorted(s)
    t = sorted(t)
    i = 0
    while i < len(s):
        if s[i] != t[i]:
            return t[i]
        else:
            i += 1
    return t[-1]

b = findTheDifference2('aacder','aacerdr')
    